services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  app:
    image: reporte_avance:0.2.3
    ports:
      - 3838:3838
    volumes:
      - .Renviron:/srv/shiny-server/app/.Renviron
    env_file:
      - .env
