services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: reportes

  app:
    image: calderonsamuel/reporte_avance:0.2.3
    ports:
      - 3838:3838
    env_file:
      - .env
    environment:
      DB_HOST: db
